sudo: required

services:
  - docker

before_install:
# Install git-lfs
- mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.2.0/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.2.0.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull

script:
- /tmp/git-lfs/git-lfs pull
# Login to Heroku registry
- docker login --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com
# Build the Docker image locally
- docker build -t registry.heroku.com/imdb-sentiment-analysis/web .
# Push the Docker image to the Heroku registry
- docker push registry.heroku.com/imdb-sentiment-analysis/web